const mongoose = require("mongoose");

const invoiceSchema = new mongoose.Schema(
  {
    // Invoice Number (unique)
    invoiceNumber: {
      type: String,
      unique: true,
      required: true
      // Format: INV-2025-000001
    },

    // Student Reference
    studentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Student",
      required: true
    },

    // Mess Payment Reference (can have multiple)
    messPaymentIds: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "MessPayment"
      }
    ],

    // Invoice Details
    invoiceDate: {
      type: Date,
      default: Date.now
    },

    dueDate: {
      type: Date,
      required: true
    },

    // Amount Details
    subtotal: {
      type: Number,
      required: true,
      min: 0
    },

    tax: {
      type: Number,
      default: 0,
      min: 0
    },

    discount: {
      type: Number,
      default: 0,
      min: 0
    },

    lateFee: {
      type: Number,
      default: 0,
      min: 0
    },

    totalAmount: {
      type: Number,
      required: true,
      min: 0
    },

    amountPaid: {
      type: Number,
      default: 0,
      min: 0
    },

    balanceDue: {
      type: Number,
      required: true,
      min: 0
    },

    // Invoice Status
    invoiceStatus: {
      type: String,
      enum: ["draft", "issued", "paid", "partially_paid", "overdue", "cancelled"],
      default: "issued"
    },

    // Payment Status
    paymentStatus: {
      type: String,
      enum: ["unpaid", "partial", "paid"],
      default: "unpaid"
    },

    // Period Covered
    periodFrom: {
      type: Date,
      required: true
    },

    periodTo: {
      type: Date,
      required: true
    },

    // Description
    description: {
      type: String,
      default: ""
    },

    // Notes
    notes: {
      type: String,
      default: ""
    },

    // Generated By
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true
    },

    // Downloaded/Viewed
    downloadCount: {
      type: Number,
      default: 0
    },

    lastDownloadedAt: {
      type: Date,
      default: null
    },

    // Reminders Sent
    reminderCount: {
      type: Number,
      default: 0
    },

    lastReminderSent: {
      type: Date,
      default: null
    }
  },
  { timestamps: true }
);

module.exports = mongoose.model("Invoice", invoiceSchema);
